In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import statsmodels.formula.api as stm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [2]:
sleep_health_and_lifestyle_df = pd.read_csv('Sleep_health_and_lifestyle_dataset.csv')

sleep_health_and_lifestyle_df.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [5]:
standardized_based_on_occupation = sleep_health_and_lifestyle_df
standard = standardized_based_on_occupation.groupby(['Occupation', 'Age'] )
for i, row in standardized_based_on_occupation.iterrows(): 
    s = (row['Sleep Duration'] - standard.get_group(row['Occupation', 'Age'])['Sleep Duration'].mean()).astype(float)
    standardized_based_on_occupation.at[i, 'standardize sleep'] = s/(standard.get_group(row['Occupation', 'Age'])['Sleep Duration'].std())

/var/folders/ny/pt579jrn2c1gc_w0x0t46b1w0000gn/T/ipykernel_19149/3235865439.py:5: RuntimeWarning: invalid value encountered in double_scalars
  standardized_based_on_occupation.at[i, 'standardize sleep'] = s/(standard.get_group(row['Occupation'])['Sleep Duration'].std())

In [6]:
standardized_based_on_occupation

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder,standardize sleep
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None,-0.747242
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None,-0.892093
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None,-0.892093
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,NaN
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,1.047142
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,0.946163
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,1.047142
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,1.047142
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,1.047142